### ISSUE TITLE
Running deepdive sql commands within an extractor?

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#11]
@ajratner @xiao-cheng, is it possible to run a deepdive sql command within an extractor using python? For example, if I wanted to perform the query:
```
deepdive sql "select * from table_dump where relation='row' AND relation_id='15' AND page_num='0' AND table_id='1'"
```
in one of my extractors, how would I do it?

**Comment by xiao-cheng** [comment]
You can import subprocess and use Popen, see https://docs.python.org/2/library/subprocess.html
