### ISSUE TITLE
Including Manufacturer Data

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#15]
While working on #13, I've realized that in order to uniquely identify a part, we need both the part number and the manufacturer. For example, multiple manufacturers make the 2N3904:

| Manufacturer | Part Number | Storage Temp |
|:------------:|:-----------:|:-------------|
|  Minilogic   |   2N3904    | -55 to 150 C |
|  Fairchild   |   2N3904    | -55 to 150 C |
|   Central    |   2N3904    | -65 to 150 C |

Right now, we don't have a way to extract the manufacturer information. Sometimes, we only have their logos on the PDFs. We will need a way to do this.

**Comment by hchiang** [comment]
One possibility is to get this info when pulling the datasheets off octopart

**Comment by lukehsiao** [comment]
That's true. For now, I'm just going to use the doc_id  as a placeholder to make the entries unique.

**Comment by hchiang** [comment]
Added pdfs with manufacturer name and part number in the name to transistor_pdf in the input folder
