### ISSUE TITLE
How should we get more training data?

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#16]
![part_temperature label](https://cloud.githubusercontent.com/assets/7573542/12188882/341a5b96-b56e-11e5-89d5-6b6ba32404f6.png)

My first go at part numbers to storage temperatures didn't look too good. I haven't tried it on the full 12,000 PDF set yet, but I assume we would want a lot more training data. How much do we need?

We can probably get some data be scraping octopart or a similar site.

**Comment by xiao-cheng** [comment]
I think 12k is enough for dev set. If we want to scrape more, I'll do it on our server. Eventually we should just run on as many as we can get (millions)

**Comment by lukehsiao** [comment]
Ah, I meant gold data we can use for distant supervision.

**Comment by xiao-cheng** [comment]
If it needs manual checking we can generate ~1k ourselves. But I think scrape some parts database for 10k~100k entries would be ideal

**Comment by hchiang** [comment]
Added about 900 specs files to the transistor_pdf folder. Will add more once I hear back from octopart about a possible issue. The specs files have the format: 
property

**Comment by hchiang** [comment]
Looks like octopart limits you to index of 1000 for queries. If we want more data, it'd be easiest to switch to a different part.

**Comment by ajratner** [comment]
Distant supervision can also be accomplished without any gold data- if you
can think of any very high-precision simple rules / heuristics, you can use
these (this is something we're currently trying to formalize more, but
empirically it seems to work!)

Should we arrange a meeting for later this week?  Sorry I missed the last
one!
