### ISSUE TITLE
Do MindTagger and BrainDump still work with DeepDive v0.7.x?

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#17]
In the next step of the tutorial application on improving results, the [tutorial webpage](http://deepdive.stanford.edu/doc/basics/walkthrough/walkthrough-improve.html) references BrainDump and MindTagger. But, it also has the warning at the top that the sections are inaccurate after DeepDive v0.6.x. Do they still work with v0.7.x? Is there other resources we should be using instead?

**Comment by xiao-cheng** [comment]
I think this is on the release schedule. The warning there probably means it already broke something in v0.7.x testing. We can just write some simple scripts for specific performance metrics.

**Comment by lukehsiao** [comment]
From Jaeho Shin:
>Hi Xiao and Luke,

>Mindtagger tutorial is still applicable, but it's not trivial to modify Braindump to work with the latest release.

>Also take a look at these code if you get confused by the webpage: https://github.com/HazyResearch/mindbender/tree/master/examples/spouse_example

>Best,
>~Jaeho
