### ISSUE TITLE
Parallelize input/init.sh to speed up loading time

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#20]
Currently, the part of the pipeline that takes the longest is when we call ```deepdive initdb``` and init.sh is run to sequentially loop through all of the input PDFs, run them through table-extraction, and add them to the ```table_dump``` table.

```sh
#!/usr/bin/env bash

set -eux
cd "$(dirname "$0")"

INPUT_FILES=pdf/*

NUM_FILES=$((ls $INPUT_FILES) | wc -l)
COUNTER=1
echo "[info] Total Number of Datasheets: $NUM_FILES"

# This loops through all of the files in pdf/ and adds them to table_dump
for f in $INPUT_FILES
do
  echo "[info] [$COUNTER/$NUM_FILES] Loading $f..."
  python ../udf/table-extraction/parse.py $f | deepdive sql "COPY table_dump FROM STDIN"
  COUNTER=$((COUNTER + 1))
done

cat create_tables.sql | deepdive sql
```

We need to speed this up.

**Comment by lukehsiao** [comment]
There are some options to do this with extra packages like [```parallel```](http://www.gnu.org/software/parallel/) or [```pexec```](http://www.gnu.org/software/pexec/), but I'm going to opt to do it just in bash, even if it's slightly less efficient.

**Comment by xiao-cheng** [comment]
You can just use xargs, see the input/decrypt.sh for example

**Comment by lukehsiao** [comment]
Thanks Xiao, that's way better.

Below are the total runtimes of ```deepdive initdb``` running various schemes.
These are processing the original 100 PDFs, running on a dual-core VM with 2GB
memory on my laptop.
|             Method              | Total Runtime |
|:-------------------------------:|:-------------:|
|       Original Sequential       |    308 sec    |
|   100% Parallelized using '&'   |    304 sec    |
| Parallel xargs (20-process max) |    271 sec    |
| Parallel xargs (2-process max)  |    253 sec    |
| Parallel xargs (4-process max)  |    289 sec    |

Hopefully the parallelization will help more on the 20-core server when we run the full 12,000 dataset.

**Comment by xiao-cheng** [comment]
Cool. Sounds about right. Intel's hyperthreading isnt real cores. It
probably gonna be I\O bound on the 48*2 thread server tho
