### ISSUE TITLE
Improving Features

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#28]
Just by adding 3 more specific features to part_storage_temperature relations:
1. same row
2. same center_col
3. same table

The calibration data looks like this:
![image](https://cloud.githubusercontent.com/assets/7573542/13166117/ef0198f4-d678-11e5-9360-b3f9af0c9d7e.png)

Yet, those same 3 features for part_collector_current relations ends up looking like this:
![image](https://cloud.githubusercontent.com/assets/7573542/13166122/01a5ffa4-d679-11e5-9bdb-94074a26ae50.png)

<del>This may be related to #27, but I'm not yet sure.</del> Probably not related.

**Comment by lukehsiao** [comment]
Update, now when I run, I get these charts:

Storage Temperature:
![image](https://cloud.githubusercontent.com/assets/7573542/13167145/e1cee946-d684-11e5-97d0-cc6f7c78f332.png)

Collector Current:
![image](https://cloud.githubusercontent.com/assets/7573542/13167153/f3824c82-d684-11e5-96d0-dbb93fb9cf52.png)

Because there is some randomness in the sampling, these charts can change between runs.

**Comment by lukehsiao** [comment]
I probably have hardcoded a fundamental limitation in the fact that by the time I am looking at features, the only data I can look at are:

```
DOC_ID   
PART_PG_NUM 
PART_TABLE_ID   
PART_RELATION 
PART_RELATION_ID   
PART_NUM  
TEMP_PG_NUM  
TEMP_TABLE_ID 
TEMP_RELATION
TEMP_RELATION_ID  
TEMP_MIN     
TEMP_MAX       
TEMP_UNIT  
RELATION_ID    
```

It may be that the best solution for this is to refactor m code so that less features are hard-coded.

**Comment by lukehsiao** [comment]
@ajratner @xiao-cheng, do you think the more general mention extractor approach will be more effective?

**Comment by xiao-cheng** [comment]
Yes it is basically the NLP tagging in the spouse example, where spans of words get a tag on them, be it PERSON, LOCATION or NUMBER etc. It definitely helps because you can get features such as "All_numbers_in_column" etc

**Comment by lukehsiao** [comment]
Great! Sounds like this is will be a worthwhile refactoring. I'll start a new branch `general_extractors` and do my refactoring there.

**Comment by lukehsiao** [comment]
@xiao-cheng:

One challenge I'm seeing as I'm getting into implementing the pairwise relations that we talked about today, is that these tables get HUGE when I don't do any filtering earlier in the pipeline. For example, when it comes time to tag features for part numbers and minimum storage temperatures, it already takes like 1.5min with the data from a single document. Is this expected? Is there any techniques I should now about to mitigate the amount of data I work with?

**Comment by xiao-cheng** [comment]
I think the answer is to take only pairs from "sentence" scope as in the spouse example, which in hour case is same table or even narrower: columns or rows

**Comment by lukehsiao** [comment]
Thanks for the feedback Xiao, I'm going to look into this today.

**Comment by hchiang** [comment]
Added stuff to the parser so now when you run it it gives the x or y coordinates of the closest left, right, top, and bottom lines for each mention (basically the dimensions of the table cell that the mention is in). Might be useful as a way to determine table hierarchy - as in is this mention's cell to the right of another mention's cell.

**Comment by lukehsiao** [comment]
Here is what the calibration plots look like when run on 100 pdfs on a local Linux desktop I just set up:
![part_stg_temp_min_label](https://cloud.githubusercontent.com/assets/7573542/13869454/4e3014de-ec92-11e5-93eb-bc8f6ee7073e.png)

I wonder why this differs from the one that we got last Saturday:
![image](https://cloud.githubusercontent.com/assets/7573542/13869461/623827dc-ec92-11e5-90f8-ca94a1f716a1.png)

These are the values of the weights of the features when I ran it this time:
```
  id  | isfixed | initvalue |                           description                            | categories |   weight    
------+---------+-----------+------------------------------------------------------------------+------------+-------------
 1453 | f       |         0 | inf_istrue_part_stg_temp_min--number_is_reasonable               |            |    0.865528
  200 | f       |         0 | inf_istrue_part_stg_temp_min--same_row_as_temperature            |            |    0.439121
  592 | f       |         0 | inf_istrue_part_stg_temp_min--same_row_as_storage                |            |    0.439121
 1630 | f       |         0 | inf_istrue_part_stg_temp_min--same_col_as_value                  |            |    0.439121
 1141 | f       |         0 | inf_istrue_part_stg_temp_min--same_row_as_tstg                   |            |    0.439121
 1748 | f       |         0 | inf_istrue_part_stg_temp_min--same_col_as_150                    |            |    0.187096
 1979 | f       |         0 | inf_istrue_part_stg_temp_min--same_row_as_range                  |            |     0.13972
 1734 | f       |         0 | inf_istrue_part_stg_temp_min--same_row_as_junction               |            |     0.13972
 1634 | f       |         0 | inf_istrue_part_stg_temp_min--same_row_as_operating              |            |     0.13972
  282 | f       |         0 | inf_istrue_part_stg_temp_min--same_row_as_150                    |            |     0.13972
 1093 | f       |         0 | inf_istrue_part_stg_temp_min--same_col_as_typ                    |            |   0.0450436
  978 | f       |         0 | inf_istrue_part_stg_temp_min--same_col_as_0                      |            |   0.0450436
  613 | f       |         0 | inf_istrue_part_stg_temp_min--same_col_as_47                     |            |   0.0450436
  653 | f       |         0 | inf_istrue_part_stg_temp_min--same_col_as_values                 |            |   0.0450436
  123 | f       |         0 | inf_istrue_part_stg_temp_min--same_col_as_storage                |            |  0.00233171
```

**Comment by lukehsiao** [comment]
After adding some features, our calibration plot looked like this:
![part_stg_temp_min_label](https://cloud.githubusercontent.com/assets/7573542/14052221/bde8b210-f285-11e5-9df6-b04dfa061dfc.png)

Following our [meeting](https://github.com/lukehsiao/HardwareDeepDive/wiki/Project-Meeting-Notes) yesterday, we identified several potential problems (e.g. class balancing problem since we only had two negative distant supervision rules). 

We will be looking into addresses these problems this weekend.

**Comment by lukehsiao** [comment]
Conclusions from our meeting today:

- [ ] The **highest priority** issue is that we currently do not have unique identifiers for our candidate objects. We need to remedy this be making unique ids. For example, we can use something like `docid_pgnum_partmentionid_valuementionid` placed in its own column. We will need to account for situations where multiple part numbers come from the same mention_id and make them unique as well.
- After that, we can look at other class balancing tricks:
  - [ ] Downsample falst example so that there is about the same ratio of false to true
  - [ ] Add a bias feature (something that fires for everything) 
  - [ ] Add more positive rules

**Comment by lukehsiao** [comment]
After the big refactor, we have **much** better looking calibration:
![part_stg_temp_min_label](https://cloud.githubusercontent.com/assets/7573542/14229927/40615296-f8f9-11e5-8370-37c44e33fab4.png)

Working on error analysis and documenting our pipeline now.

**Comment by xiao-cheng** [comment]
Also we need to note in the document that our setup is moving to multinomial instead of binary classification.

**Comment by lukehsiao** [comment]
Closing this issue since we are not moving on to the new context of multinomial classification. The original issue of improving calibration data on a binary classification has been resolved.
