### ISSUE TITLE
How to add clear table extractor

### ISSUE THREAD

**Issue by hchiang** [lukehsiao/HardwareDeepDive#29]
We have this issue where every time we run deepdive the tables get larger and larger. We'd like to add a clear table extractor like the following, from the tutorial example: 

```
# Extractor 1: Clean output tables of all extractors
    ext_clear_table {
      style: "sql_extractor"
      sql: """
        DELETE FROM people_mentions;
        DELETE FROM has_spouse;
        DELETE FROM has_spouse_features;
        """
    }
```

The problem however is that most of our extractors are implemented in the app.ddlog file, and I'm not sure if we can just add SQL statements like this to the app.ddlog file? Otherwise, I'd like to put it in deepdive.conf, like in the example, but the rest of our extractors are in app.ddlog and I'm not sure how to add a dependency such that the ext_clear_table executes before any of our other extractors, so that it doesn't end up erasing the tables after we've extracted them.

**Comment by xiao-cheng** [comment]
I think you should do
```
deepdive initdb
```
before every `deepdive run`.

If it is too slow on the entire dev set, maybe try on a single file.

**Comment by hchiang** [comment]
initdb takes a while though, which is why we'd like to implement the clear table extractor to speed up the process. Is there a way to add SQL to app.ddlog?

**Comment by lukehsiao** [comment]
It takes about 4mins each time to do deepdive initdb on the set of 100pdfs. It would be great if we could implement something that cleared the extra tables (besides table_dump) each time `deepive run` was called.

**Comment by xiao-cheng** [comment]
http://stackoverflow.com/questions/2829158/truncating-all-tables-in-a-postgres-database
Maybe just write a script called reset_tables.sh that clear all tables starts with "dd_"?

@lukehsiao Maybe your duplication problem is related to this as well?

**Comment by lukehsiao** [comment]
This is easy to do in DeepDive v0.8.0. I'm going to close this issue for now.
