### ISSUE TITLE
Update deepdive code to work with latest table-extraction

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#30]
Holly's line addition to [table-extraction](https://github.com/xiao-cheng/table-extraction/commit/5ff9a7e8bcd28f23888e3a75c622993b9427fec1) now outputs floats as relation-id. I will need to update the DeepDive code to allow this.

**Comment by hchiang** [comment]
We can just round to the nearest int without losing much info

**Comment by lukehsiao** [comment]
Hmm, that would save me some work. Could you do that?

**Comment by lukehsiao** [comment]
Going to close this for now as we are using HTML.
