### ISSUE TITLE
Optimize tagger performance

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#34]
Right now, the taggers run on every cell.

We could reduce the amount of computations that they are doing by using the computations already performed for the siblings.

**Comment by xiao-cheng** [comment]
1. Store lowercase, cleaned `aligned_with_*` feature for each cell, so siblings can just reuse them
2. The tagger should keep the original surface string

**Comment by lukehsiao** [comment]
I'm currently only getting 88/99 documents represented in the `part_stg_temp_min_candidates`. I'm looking into why that is the case.

**Comment by xiao-cheng** [comment]
```
hwdeepdive=# select count(distinct doc) from mentions where tag = 'part_num';
 count
-------
    97
(1 row)
```

```
hwdeepdive=# select count(distinct doc) from mentions where tag = 'num' and surface::float < 0 and surface::float > -80;
 count
-------
    89
(1 row)
```

**Comment by lukehsiao** [comment]
Yeah that's what I'm seeing. I have the 2nd query at 91 now, which seems good enough.

**Comment by xiao-cheng** [comment]
I'd say don't worry about these things, look at the output and check for 2 types of errors:
1. Gold said yes but we said no
2. We said yes but gold said no ( which might be noise in gold )

**Comment by lukehsiao** [comment]
Sounds good.

**Comment by lukehsiao** [comment]
It's correct to be doing this analysis from `part_stg_temp_min_label_inference`, right?

```
deepdive sql "SELECT p_uid, p_surface, t_uid, t_surface, label, expectation from part_stg_temp_min_label_inference where label is not NULL order by p_uid, p_surface, t_uid, t_surface, label, expectation"
```

Right off the bat, I notice some that gold says yes (since gold is simply looking at part numbers and values for min stg temp), but DeepDive says no. For example:
```
               p_uid               | p_surface |               t_uid               | t_surface | label | expectation 
-----------------------------------+-----------+-----------------------------------+-----------+-------+-------------
 112823.pdf@2@0                    | BC546B    | 112823.pdf@2@134                  | -55       | t     |       0.058
 112823.pdf@2@2                    | BC547A    | 112823.pdf@2@134                  | -55       | t     |       0.049
 112823.pdf@2@4                    | BC548B    | 112823.pdf@2@134                  | -55       | t     |       0.038
```
However, if you look at the document, DeepDive is definitely correct in saying this is false since the -55 is just coming from some random graph unrelated to storage temperature.

**Comment by xiao-cheng** [comment]
Deepdive is training on a mention level, we evaluate at document level.
Document level gold data is used as a rule of thumb to supervise mention level extraction.
So I think these do not count as errors.

**Comment by lukehsiao** [comment]
I agree, so I'm just going to base my error analysis off of the expectations in `part_stg_temp_min_label_inference`.

**Comment by xiao-cheng** [comment]
Would be nice to have the p/r numbers: https://en.wikipedia.org/wiki/Precision_and_recall
precision = # of pairs we labeled correctly as true / things we say is true
recall       = # of pairs we labeled correctly as true / things gold say is true

**Comment by lukehsiao** [comment]
I'm on it.

**Comment by lukehsiao** [comment]
This would be easier to find if we had a way of counting the distinct pairs of part->stg_temp_min for each document. Something like...
```bash
deepdive sql "SELECT (DISTINCT doc_id, p_surface, t_surface), label, expectation from part_stg_temp_min_label_inference where label=true"
```
This isn't valid SQL, but I'm not sure of a good way to accomplish this. Any ideas?
