### ISSUE TITLE
Decouple this repository and table-extraction

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#35]
At some point, we can decouple these two repositories. 'table-extraction` doesn't need to be a submodule, we just need the dump.tsv produced by table extraction in this repository.

**Comment by xiao-cheng** [comment]
Agreed, and I can remove the lock used for printing to stdout

**Comment by lukehsiao** [comment]
This is done for `general-ext`. I'm working on cleaning up files before I pull request into `master`.
