### ISSUE TITLE
Define Interface between Table-Extraction and DeepDive

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#4]
In the normal DeepDive pipeline, a PDF is put through NLP which parses the text and adds metadata. Then, DeepDive applications are written to process this NLP-generated data.

For our application, we should define/discuss what the interface between [Table Extraction](https://github.com/xiao-cheng/table-extraction|) and DeepDive will be.

**Comment by lukehsiao** [comment]
After our [meeting](https://github.com/lukehsiao/HardwareDeepDive/wiki/Project-Meeting-Notes#5-nov-2015) today, it sounds like the interface will be similar to an HTML tree. That is, for a given value, we should know the horizontal alignment, vertical alignment, and whether values are adjacent to each other. We will still probably want to formalize what it looks like [on the wiki](https://github.com/lukehsiao/HardwareDeepDive/wiki/Input-Data-Interface) once we have decided.

**Comment by xiao-cheng** [comment]
See https://github.com/xiao-cheng/table-extraction#output
