### ISSUE TITLE
Unify taggers

### ISSUE THREAD

**Issue by xiao-cheng** [lukehsiao/HardwareDeepDive#43]
Currently we are extracting `92` as `num` from `TO-92` and `C` as `unit` from `BC546A,B,C`.
From the learning perspective these are not really valid candidates and our gold data has no way of indicating this is a false positive and we pay both statistical and hardware performance penalty for this.

Maybe add to the test cases? The first check for word boundary before the number and negative sign.
The second require the entire cell to be a single unit string or a num+unit combo, reject otherwise.

**Comment by lukehsiao** [comment]
I'm on it!

**Comment by xiao-cheng** [comment]
Also it is extracting `c` from `Ic`. So check for upppercase in your unit regex lookahead

**Comment by xiao-cheng** [comment]
A good way (also how I came across these) is to look at the mention table and see if there are strange large chunks of extractions that came out of no where

**Comment by lukehsiao** [comment]
This is where distant supervision rules could help fix the labels, correct? Gold data might say true, but some distant supervision rules based on features might indicate that it is false?

**Comment by xiao-cheng** [comment]
I think supervision is only for distinguishing `c` between different types of temperatures, not whether a string is the temperature unit or not, the latter unnecessarily blows up the example space that we can not do more advanced inferences such as max value for type must > min value because there are too many pairs that drowns the useful signals.

Also it is extracting numbers from `BC546B/547B/548B`

**Comment by xiao-cheng** [comment]
Just as in the spouse example we don't join every word in corpus with every other word to find out which words are people names

**Comment by xiao-cheng** [comment]
As the title suggest, my initial thoughts were to unify taggers so you don't extract numbers from strings that already matched to parts. This is needed later on anyway, where you don't extract numbers from dates etc. Just put all taggers in a single function and do a bunch of if then to avoid duplicate extractions

**Comment by lukehsiao** [comment]
I see. Where part numbers is highest priority? That's the only separation, I believe. We'll need to be able to extract both unit and number from something like `150C`.

**Comment by xiao-cheng** [comment]
Yes, use a list of substrings that persists across taggers, remove the parts that has been extracted

**Comment by lukehsiao** [comment]
Ok. I'll look into this. I'll probably make the Tagger it's own class.

**Comment by xiao-cheng** [comment]
You can also define a combined tagger for things like `150C` that spits out two things a time, which is higher priority that separate extractions
