### ISSUE TITLE
Gold annotation for ce_v_max check

### ISSUE THREAD

**Issue by xiao-cheng** [lukehsiao/HardwareDeepDive#47]
```
17:18:49 [xiao@xc2 scripts]$ ./show_docs_with_no_pos_label.sh ce_v_max
     doc
--------------
 MCCCS08818-1
 PJECS00521-1
 RECTS01158-1
 RECTS01214-1
 RECTS01325-1
 UTCLS03593-1
 VSMIS00373-1
 VSMIS03793-1
 dtc114w
(9 rows)
```
` PJECS00521-1` has corrupted text
`MCCC*`,`dtc114w` and `RECT*` do not have this relation I think, please re-annotate some of them
`VSMI` is the missing part number so don't worry about it

**Comment by lukehsiao** [comment]
`RECTS01158-1` is correct: https://github.com/lukehsiao/HardwareDeepDive/blob/master/input/pdf/RECTS01158-1.pdf

**Comment by lukehsiao** [comment]
What do you mean by corrupted text on `PJEC*`?

**Comment by lukehsiao** [comment]
the `VSMI*` ones are also correct already.

**Comment by lukehsiao** [comment]
`UTCL*` also has null because it doesn't have the relation.

**Comment by xiao-cheng** [comment]
Ok sorry about that ! I was using the wrong gold table with null values in it.
```
17:56:04 [xiao@DN0a18163a scripts]$ ./show_docs_with_no_pos_label.sh ce_v_max
     doc
--------------
 PJECS00521-1
 RECTS01158-1
 VSMIS00373-1
 VSMIS03793-1
(4 rows)
```
I think the RECT PDF is corrupt on my machine and multiclass branch, will pull from master
