### ISSUE TITLE
Some part numbers appear truncated

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#49]
If we look at
```bash
cd scripts/
./rerun
./evaluate ce_v_max
deepdive sql 'SELECT * from ce_v_max_extractions WHERE prob > 0.5'
```
some part numbers appear truncated:
```
2N5088BU-Fairchild-datasheet-6029                    | 2N2           | 25   | 0.834
2N5088BU-Fairchild-Semiconductor-datasheet-10036204  | MMBT2         | 30   | 0.869
2SA1037AKT146Q-Rohm-datasheet-511857                 | 2SC2          | -50  | 0.999
```

This occurs in several documents including, but not limited to:
- 2N6109G-ON-Semiconductor-datasheet-11547311
- 2N6111G-ON-Semiconductor-datasheet-21210821
- 2SA1037AKT146Q-Rohm-datasheet-8252
- 2SA1774TLR-Rohm-datasheet-41194705

Also note that we only capture 680 distinct documents in this table of the 1099 documents processed.

In contrast, we get 1002 distinct docs from stg_temp_min_extraction.

**Comment by lukehsiao** [comment]
I don't think this is a problem in the tagger, it may be a bug in ext_mentions.

**Comment by lukehsiao** [comment]
`doc_features['parts']`inside `ext_mentions` contains:
```
set(['2N6107', '1N5825', '2N92', '2N6111', '2N11', '2N6107G', '2N90', '2N6109', '2N6107D', '2N6288G', '2N6109G', '2N6292G', '2N922', '2N09', '2N6292', '2N2', '2N6111G', '2N6288']) 
```
For example, 2N2 in this case.

Within `ext_mentions` I see:

"PNP - 2N6107, 2N6109, 2N6111; NPN - 2N6288,"

outputting: 2N6107, 2N2, 2N6109, 2N2, 2N6111, 2N6288

**Comment by lukehsiao** [comment]
Fixed by passing the inferred part numbers through the regex for a 2nd pass of validation.

**Comment by xiao-cheng** [comment]
I think combination triggers should be limited to A,B,C...and numbers

**Comment by lukehsiao** [comment]
It is, it just saw "2N6107, 2" so it swapped the 6107 to 2.
