### ISSUE TITLE
Scrape for 10,000s of Small-Signal Bipolar Transistor PDFs

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#5]
Eventually, we will need a much larger set of PDFs. We can create a web scraper to start gathering them so that this won't become a bottleneck later.

**Comment by hchiang** [comment]
I pushed a pdf extractor to the pdfextractor branch. Right now it's configured to scrape for solid state relays, you can change that to whatever you'd like. To set the number of datasheets to extract, change the limit number. Right now it extracts parts alphabetically.

**Comment by hchiang** [comment]
Also, if you uncomment out the specs and descriptions, the data from that can be used as a gold standard

**Comment by lukehsiao** [comment]
For example, changing the query to "Epitaxial Silicon Transistor" will get you datasheets from the same category as our sample dataset.

**Comment by xiao-cheng** [comment]
@lukehsiao PDF that needs OCR will be ignored automatically - there will be no text to extract. Unless this is a significant percentage (>5%) of them, I wouldn't worry about filter them.

**Comment by lukehsiao** [comment]
I can start scraping for datasheets this week. My estimate is that I can probably get about 15k-20k transistor datasheets that are similar to the dataset that we already have.

**Comment by lukehsiao** [comment]
For reference:
[OctoPart's REST API Reference](https://octopart.com/api/docs/v3/rest-api#object-schemas-datasheet) describes the what the objects and format of search responses are. In our code, we perform a SearchRequest, and get a [SearchResponse](https://octopart.com/api/docs/v3/rest-api#response-schemas-searchresponse). This SearchResponse contains SearchResults, from which we can pull [Parts](https://octopart.com/api/docs/v3/rest-api#object-schemas-part). 

A part contains lots of useful information. For our scraper, we are going through the list of datasheets associated with the part and downloading from the provided URL. In the future, we can even pull reference designs or specs as well.

One caveat is that each SearchRequest will return a _maximum_ of 100 results. So, the script must be broken up into several iterations of SearchRequests. 

I'm currently in process of scraping for datasheets and will refine the script as I go.

**Comment by hchiang** [comment]
There’s stanford Box, which apparently lets you share files

**Comment by lukehsiao** [comment]
Here is a link to 12,423 PDFs. 

[Transistor PDF Dataset](https://stanford.box.com/s/qqec3t1j2mje7ih3c8turfcmt2298yvb)

I can always get more if we want/need more. Note that there are several PDFs in here that are irrelevant (e.g. datasheets that is only the dimensions of the transistors, datasheets for other components like capacitors or diodes, etc.). I assume that these are still OK to have in here. If we need more refined results, let me know. The vast majority of the PDFs are relevant.

**Comment by lukehsiao** [comment]
Closing this for now. If we need more, we can reopen this task. I'll add the dataset to the wiki.
