### ISSUE TITLE
Update docs and perform error analysis for dc_gain_min

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#50]
We've updated our pipeline, so we need to update the documentation. It would also be useful to understand the errors in dc_gain_min by doing an error analysis for that relation, since it has the lowest F1, and is a challenging relation to extract.

**Comment by xiao-cheng** [comment]
Use the `script/show_[high|low]_.*` to see the 2 types of errors, would be nice to know the percentage of errors caused by PDF-> HTML conversion

**Comment by lukehsiao** [comment]
Nice scripts. How do you turn of the spacing between columns so that a view is a lot denser?

**Comment by lukehsiao** [comment]
@xiao-cheng: What do you suggest we do to classify errors like this:

![positioning](https://cloud.githubusercontent.com/assets/7573542/15060682/44a19052-12e2-11e6-98b6-bd3a87fcb008.gif)

In this case, the `under_hfe` feature is missing from the group of part numbers in the big cell. But then there is the challenge that all those part numbers are in a big cell, rather than individual rows like their corresponding dc_gain_min values.

**Comment by lukehsiao** [comment]
Looking at the way some of these document describe DC Gain, there is also the complexity that DC Gain is not just a static value. For example in `2N3906-D`, there is only a single part number and we see this:
![image](https://cloud.githubusercontent.com/assets/7573542/15061234/935481f0-12e7-11e6-8643-d2c95837133b.png)

This is because the minimum DC gain actually changes depending on the collector current. It's a curve. Most datasheets just pick a few points on this curve. So, it may also be that we are looking for a value that isn't well described by table entries. 

In the case of `2N3906-D`, the value of `30` was chosen just because it was the smallest of all of the values shown.

**Comment by xiao-cheng** [comment]
Can you check the grid output by putting 112823 in the debug variable for
ext_mention.py? It should be resolved, but might be misaligned due to html

**Comment by lukehsiao** [comment]
Yeah, I'll check that now.

**Comment by lukehsiao** [comment]
After looking through many of the documents, I think that it's not only the PDF to HTML step that is hard, but also just interpreting the documents.

## Examples:
### 1. Unclear HTML
`BC546A_Series_B14-521026.html` has some misaligned HTML, but most of the time it seems to be aligned reasonably.
![image](https://cloud.githubusercontent.com/assets/7573542/15065012/b4845440-130f-11e6-925a-5e8b5d4f27a4.png)

### 2. Many Data Points
What also seems difficult is that many PDFs have tables like this:
![image](https://cloud.githubusercontent.com/assets/7573542/15065031/e3717a58-130f-11e6-955c-e5b0499255c9.png)

Where several points of the DC Gain curve are picked out and placed in the table (`DISES00023-1.html`)

### 3. Split Tables
We also struggle when they split up the Gain into two different tables like this:
![image](https://cloud.githubusercontent.com/assets/7573542/15065053/24219880-1310-11e6-9893-4820e9ff63fc.png)
(see `bc550.html`)

### 4. Multiple Headers
We also struggle for some of the PDFs like this:
![image](https://cloud.githubusercontent.com/assets/7573542/15065062/450fd5c0-1310-11e6-9833-63a2bfe99725.png)

Where the candidates end up being associated with several different headers.

These seem to be the types of documents that cause us to have low expectation for true candidates.

**Comment by xiao-cheng** [comment]
Very cool! Now we know what kinda of HTML we need to validate the parsers
with :D

**Comment by xiao-cheng** [comment]
meanwhile it might be good to formalize things that needs to be mutually exclusive (can't be two things at the same time):
part numbers, attribute names, conditions etc.

**Comment by lukehsiao** [comment]
So at a first pass, the two largest causes of errors are:
1. Not being able to associate a value with a specific part. For example, when a document just has Group A [values] and Group B [values] on the next row. This affected about 120 entries.
2. Having to entry for a true value at all. This may mean that the number is being parsed incorrectly, or it may not be a candidate in the first place. This affected about 70 entries.

There are quite a few documents where the HTML appears to be misaligned. But, the majority of those we would also fail to associate the parts with the specific numbers anyways.
