### ISSUE TITLE
Symbols in HTML output

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#51]
I noticed that some of the HTML output contains symbols like this: 

![image](https://cloud.githubusercontent.com/assets/7573542/15259097/14e7c142-1904-11e6-8620-ecf3c8660086.png)

Does this cause any issues when parsing the text?

**Comment by xiao-cheng** [comment]
No these are ignored

**Comment by lukehsiao** [comment]
Is the information just dropped, or do we still get the correct data as output?

**Comment by xiao-cheng** [comment]
since it is not ascii, it is not recognized as a word

**Comment by lukehsiao** [comment]
Hmm ok. This does occasionally corrupt the unit column, which may cause us to lose valuable data. This is a smaller percentage though.

**Comment by xiao-cheng** [comment]
Don't worry about these HTML problems, these will be fixed once we have control over HTML parsing
