### ISSUE TITLE
Create HTML templates to generate pdfs for different manufacturer

### ISSUE THREAD

**Issue by xiao-cheng** [lukehsiao/HardwareDeepDive#52]
1. Take the Acrobat HTML output for one particular style of datasheet
2. Clean up the HTML so that it actually looks like the pdf page (not much visual artifact)
3. Replace all things you want to extract with variable names such as $PART_NUM, $DC_MIN_VAL
4. Assign classes to these HTML elements that could use different styles so that we can apply different CSS to make the page look different and thus generate more robust training data
5. Repeat for a few more styles

**Comment by lukehsiao** [comment]
Do you have an example?

**Comment by lukehsiao** [comment]
This is done in Xiao's other repository: [HTML Generator](https://github.com/xiao-cheng/html-generator)
