### ISSUE TITLE
Generate rules to map from table-extractor output to database schema

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#6]

**Comment by lukehsiao** [comment]
@xiao-cheng Is there anything you can point me to as a reference that talks about what makes good rules? 

I'm currently looking at the [DeepDive Tutorial](http://deepdive.stanford.edu/doc/basics/walkthrough/walkthrough.html) as well as [Writing Inference Rules](http://deepdive.stanford.edu/doc/basics/inference_rules.html). It seems that the if-then type logic Alex was talking about only makes up the *factor function* portion of an inference rule, right?

What types of rules would be most useful for me to start creating? I'm currently set up to try to define rules on how things could be matched to our output schema. I will use [this wiki page](https://github.com/lukehsiao/HardwareDeepDive/wiki/Inference-Rules) as the place where we store our ideas.

**Comment by xiao-cheng** [comment]
@lukehsiao Currently I think the most natural thing to do is to type the "mention"s, i.e. given a string in a cell, is it normal text? is it a part number? is it a quantity w/ or w/o unit, basically some regex or closed set to identify the mentions of interest in the table contents.

**Comment by hchiang** [comment]
Added a script that takes the table extractor data and properly assigns rows and columns. Works well on the first page of the 112823 files, haven't had the chance to test it on more files.

**Comment by lukehsiao** [comment]
Closing this issue since this one is being accomplished through writing extractors and developing the DeepDive code. This was created when we weren't really sure what the next steps were. Now, we have some clear next steps.
