### ISSUE TITLE
Scrape for Op-Amp Datasheets

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#60]
I'll scrape for a good starting set of op-amp datasheets so we can start evaluating op-amps.

**Comment by lukehsiao** [comment]
Using Holly's scraper (updated to skip over some bad URLs) as seen in 9b2bee0.

Once they're done downloading I'll zip them and post a link to the files here. 

We may want to start a new repo for op-amps.

**Comment by lukehsiao** [comment]
# 1000 Op Amp Datasheets:
Downloadable from [Box.com](https://stanford.box.com/s/u56hea02jh76g09il5douuvfv2tdbfhd) (1.1GB). Download it onto your local machine when possible.

**Comment by xiao-cheng** [comment]
Is it similar to the transistor ones? Maybe a few dev samples from diff manufacturers would be good

**Comment by lukehsiao** [comment]
Yep, similar. I have several different manufacturers there.
