### ISSUE TITLE
Enable extraction on encrypted pdfs

### ISSUE THREAD

**Issue by xiao-cheng** [lukehsiao/HardwareDeepDive#7]
Some PDFs have disabled copying: (the following commands require ghostscript and xpdf libraries, which you can sudo apt-get install)
```
pdfinfo input/pdf/2N3906.pdf | grep -P 'Encrypted: *yes'
```
We should run some scripts to get the normal versions before doing the extraction:
```
gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=$OUTPUT -c .setpdfwrite -f $INPUT
```

**Comment by xiao-cheng** [comment]
Added a script for this:
https://github.com/lukehsiao/HardwareDeepDive/blob/dev/input/decrypt.sh

**Comment by lukehsiao** [comment]
Justs heads up, we will need to run our large dataset through this script.
