### ISSUE TITLE
Fix error in Gold Data CSV

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#81]
![image](https://cloud.githubusercontent.com/assets/7573542/18405517/6849dca2-76a7-11e6-9103-a6eb3da66beb.png)

This part needs to be updated in the repository.

**Comment by lukehsiao** [comment]
I'm starting to think that to make this simpler, we may just want to have only data-point for `dc_gain_min`. For example, at the typical test conditions of `Ic = 2.0mA Vce = 5.0V` that is commonly seen on datasheets. Then, only take the most specific value. For example, rather than associating BC550B with 110 and 200, only associate it with 200.

**Comment by hchiang** [comment]
For later applications though, we probably want more data. I think it'd be more effective to extract it all and then filter at the application level.

**Comment by lukehsiao** [comment]
@hchiang: That's a fair point. With your heuristics that definitely seems possible. With a machine learning approach is seems we are stuck in the sense that we are looking to train the system to do binary classification on a predefined relationship. I don't think there is any getting around "knowing what you want to know" beforehand at least in terms of relations for the Snorkel/DeepDive approach.

**Comment by lukehsiao** [comment]
After talking with Phil, we deiceded to add all of the parts on the datasheets (including the ones that specify ordering / package types) to the gold data. Working on that sheet now.

Afterwords, will make a version of the gold that trims the DC gain mins.
