### ISSUE TITLE
Create a script to turn the tsv output of Xiao's table-extractor into CSVs for input into PostgreSQL database

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#9]
Xiao's Table Extractor gives us output that looks like this:
```
relation	relation_id	mention_text	mention_id
row	0	Rating	0
row	0	Symbol	1
row	0	Value	2
row	0	Unit	49
```
Which is easy to directly convert directly into a CSV and input into the postgresql database using the command:
```deepdive sql "COPY table_dump FROM STDIN CSV" < [filename.csv]```

to get this:
```
relation  | relation_id |              mention_text               | mention_id
----------+-------------+-----------------------------------------+------------
row       |           0 | Rating                                  |          0
row       |           0 | Symbol                                  |          1
row       |           0 | Value                                   |          2
row       |           0 | Unit                                    |         49
```

However, in order to have a single database where all table values can be dumped, we need to add a column of filename, so that it looks like this:
```
relation  | relation_id |              mention_text               | mention_id |    filename
----------+-------------+-----------------------------------------+------------+-----------------
row       |           0 | Rating                                  |          0 | 112823-0-1.csv
row       |           0 | Symbol                                  |          1 | 112823-0-1.csv
row       |           0 | Value                                   |          2 | 112823-0-1.csv
row       |           0 | Unit                                    |         49 | 112823-0-1.csv
```

It seems like the easiest approach to this will just be to write our own script which will take the output of Xiao's table-extractor, and turn them into CSV files with the filename column. Having our own script will let us change things more easily later on.

**Comment by xiao-cheng** [comment]
I'm in the process of changing the output schema to allow assign global mention ids so I'd say you can skip working on this. Also I think psql can take tsv files just fine (COPY FROM STDIN TSV)

**Comment by lukehsiao** [comment]
For global mention_ids, I'm not sure if that will solve my problem. The original issue is that if I load multiple tables from multiple files into a schema like this:
```
relation  | relation_id |              mention_text               | mention_id
----------+-------------+-----------------------------------------+------------
row       |           0 | Rating                                  |          0
row       |           0 | Symbol                                  |          1
row       |           0 | Value                                   |          2
row       |           0 | Unit                                    |         49
```
I need to be able to isolate a single table to do processing on it. For example, associate the cells under "Symbol" as a symbol, but only for this particular table. Will the format of your globally-unique mention_ids make it easy to tell which rows are from the same table, and which are not?

As for taking TSV files, it's not listed in their [documentation](http://www.postgresql.org/docs/current/static/sql-copy.html), only CSV files are.

When I tried using ``` deepdive sql "COPY table_dump FROM STDIN TSV" < ./112823.pdf-0-1.tsv ```
I get this error:
```
+ deepdive sql 'COPY table_dump FROM STDIN TSV'
ERROR:  syntax error at or near "TSV"
LINE 1: COPY table_dump FROM STDIN TSV
```
Is there a way to get TSVs to work?

**Comment by xiao-cheng** [comment]
For the global id, the schema is:
headers = ['doc_id', 'page', 'table_id', 'relation', 'relation_id', 'mention_text', 'mention_id']
you can separate out a table conditioned on the first 3 fields. There will also be page specific headers that are not associated with any tables, so this is more flexible.

For tsv you can just drop the tsv modifier. See the https://github.com/lukehsiao/HardwareDeepDive/blob/dev/input/init.sh for example

**Comment by lukehsiao** [comment]
Ah, I see. This looks really good! I'll close this issue and checkout what you changed.
